upstream discourse_app {
  server 127.0.0.1:9292;
}

server {
  listen 80 default_server;
  server_name _;

  root /var/www/discourse/public;

  client_max_body_size 100m;

  proxy_http_version 1.1;
  proxy_buffering off;
  proxy_read_timeout 300;
  proxy_send_timeout 300;

  location /assets/ {
    root /var/www/discourse/public;
    gzip_static on;
    expires max;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }

  location /stylesheets/ {
    root /var/www/discourse/public;
    gzip_static on;
    expires max;
    add_header Cache-Control "public, immutable";
    try_files $uri @discourse;
  }

  location /theme-javascripts/ {
    root /var/www/discourse/public;
    gzip_static on;
    expires max;
    add_header Cache-Control "public, immutable";
    try_files $uri @discourse;
  }

  location /extra-locales/ {
    root /var/www/discourse/public;
    gzip_static on;
    expires max;
    add_header Cache-Control "public, immutable";
    try_files $uri @discourse;
  }

  location /uploads/ {
    root /var/www/discourse/public;
    expires max;
    add_header Cache-Control "public";
    try_files $uri @discourse;
  }

  location /optimized/ {
    root /var/www/discourse/public;
    expires max;
    add_header Cache-Control "public";
    try_files $uri @discourse;
  }

  location /plugins/ {
    root /var/www/discourse/public;
    expires max;
    add_header Cache-Control "public";
    try_files $uri @discourse;
  }

  location /downloads/ {
    internal;
    alias /var/www/discourse/;
  }

  location / {
    try_files $uri @discourse;
  }

  location @discourse {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_set_header X-Accel-Mapping /var/www/discourse/=/downloads/;

    proxy_pass http://discourse_app;
  }
}